Table.TransformColumnTypes(Source, {{"As of Date", type date}})
