let
  StartDate = #date(2023, 10, 1),
  EndDate = #date(2028, 9, 30),
  DateList = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
  DateTable = Table.TransformColumnTypes(Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error), {{"Date", type date}}),
  AddFiscalYear = Table.TransformColumnTypes(Table.AddColumn(DateTable, "FY", each if Date.Month([Date]) >= 10 then Date.Year([Date])+1 else Date.Year([Date])), {{"FY", Int64.Type}}),
  AddFiscalMonth = Table.TransformColumnTypes(Table.AddColumn(AddFiscalYear, "FM", each if Date.Month([Date]) >= 10 then Date.Month([Date]) - 9 else Date.Month([Date]) + 3), {{"FM", Int64.Type}}),
  AddFiscalQuarter = Table.TransformColumnTypes(Table.AddColumn(AddFiscalMonth, "Fiscal Qtr", each Number.RoundUp([FM] / 3)), {{"Fiscal Qtr", Int64.Type}}),
  AddStartOfFiscalYear = Table.AddColumn(AddFiscalQuarter, "Start of Fiscal Year", each #date([FY]-1, 10, 1), type date),
  AddEndOfFiscalYear = Table.AddColumn(AddStartOfFiscalYear, "End of Fiscal Year", each #date([FY], 9, 30), type date),
  AddStartOfFiscalMonth = Table.AddColumn(AddEndOfFiscalYear, "Start of Fiscal Month", each Date.StartOfMonth([Date]), type date),
  AddEndOfFiscalMonth = Table.AddColumn(AddStartOfFiscalMonth, "End of Fiscal Month", each Date.EndOfMonth([Date]), type date),
  AddStartOfFiscalQuarter = Table.AddColumn(AddEndOfFiscalMonth, "Start of Fiscal Quarter", each Date.StartOfQuarter([Date]), type date),
  AddEndOfFiscalQuarter = Table.AddColumn(AddStartOfFiscalQuarter, "End of Fiscal Quarter", each Date.EndOfQuarter([Date]), type date),
  AddQwithFQ = Table.AddColumn(AddEndOfFiscalQuarter, "Fiscal Quarter", each "Q" & Text.From([Fiscal Qtr], "en-US"), type text),
  AddYear = Table.TransformColumnTypes(Table.AddColumn(AddQwithFQ, "Year", each Date.Year([Date])), {{"Year", Int64.Type}}),
  AddMonth = Table.TransformColumnTypes(Table.AddColumn(AddYear, "Month", each Date.Month([Date])), {{"Month", Int64.Type}}),
  AddQuarter = Table.TransformColumnTypes(Table.AddColumn(AddMonth, "Quarter", each Date.QuarterOfYear([Date])), {{"Quarter", Int64.Type}}),
  addFY = Table.AddColumn(AddQuarter, "Fiscal Year", each "FY" & Text.End(Text.From([FY], "en-US"), 2), type text),
  AddFiscalYearQuarter = Table.AddColumn(addFY, "Fiscal Year Quarter", each Text.Combine({Text.From([FY], "en-US"), Text.From([Fiscal Qtr], "en-US")}, "00"), type text),
  AddFiscalYearMonth = Table.AddColumn(AddFiscalYearQuarter, "Fiscal Year Month", each Text.From([FY]) & Text.PadStart(Text.From([FM]), 3, "0"), type text),
  CurrDt_Index = if List.Max(AddStartOfFiscalMonth[Date]) > DateTime.Date(DateTime.FixedLocalNow()) then DateTime.Date(DateTime.FixedLocalNow()) else Date.AddDays(List.Max(AddStartOfFiscalMonth[Date]), -1),
  CurrDt_Start_Fmo_Index = Record.Field(Table.Min(Table.Buffer(Table.SelectRows(AddFiscalYearMonth, each [End of Fiscal Month] > CurrDt_Index)), "Start of Fiscal Month"), "Start of Fiscal Month"),
  AddFiscalMonthOffset = Table.AddColumn(AddFiscalYearMonth, "Fiscal Month Offset", each Number.Round(Number.From([Start of Fiscal Month] - CurrDt_Start_Fmo_Index) / 30, 0), Int64.Type),
  CurrDt_Start_Fqtr_Index = Record.Field(Table.Min(Table.Buffer(Table.SelectRows(AddFiscalMonthOffset, each [End of Fiscal Quarter] > CurrDt_Index)), "Start of Fiscal Quarter"), "Start of Fiscal Quarter"),
  CurrDt_Start_Fyr_Index = Record.Field(Table.Min(Table.Buffer(Table.SelectRows(AddFiscalMonthOffset, each [End of Fiscal Year] > CurrDt_Index)), "Start of Fiscal Year"), "Start of Fiscal Year"),
  Add_Fiscal_Qtr_Offset = Table.AddColumn(AddFiscalMonthOffset, "Fiscal Quarter Offset", each Number.Round(Number.From([Start of Fiscal Quarter] - CurrDt_Start_Fqtr_Index) / 90, 0), Int64.Type),
  Add_Fiscal_Year_Offset = Table.TransformColumnTypes(Table.AddColumn(Add_Fiscal_Qtr_Offset, "Fiscal Year Offset", each Number.Round(Number.From([Start of Fiscal Year] - CurrDt_Start_Fyr_Index) / 365, 0)), {{"Fiscal Year Offset", Int64.Type}}),
  ref_FiscalStartCalendar = List.Min(Add_Fiscal_Year_Offset[Start of Fiscal Year]),
  AddSequentialFiscalYear = Table.TransformColumnTypes(Table.AddColumn(Add_Fiscal_Year_Offset, "Sequential Fiscal Year", each 1 + Number.Round(Number.From([Start of Fiscal Year] - ref_FiscalStartCalendar) / 365 , 0)), {{"Sequential Fiscal Year", Int64.Type}}),
  AddSequentialFiscalQuarter = Table.TransformColumnTypes(Table.AddColumn(AddSequentialFiscalYear, "Sequential Fiscal Quarter", each 1 + Number.Round(Number.From([Start of Fiscal Quarter] - ref_FiscalStartCalendar) / 90 , 0)), {{"Sequential Fiscal Quarter", Int64.Type}}),
  AddSequentialFiscalMonth = Table.TransformColumnTypes(Table.AddColumn(AddSequentialFiscalQuarter, "Sequential Fiscal Month", each 1 + Number.Round(Number.From([Start of Fiscal Month] - ref_FiscalStartCalendar) / 30 , 0)), {{"Sequential Fiscal Month", Int64.Type}})
in
    AddSequentialFiscalMonth
